import { Ionicons } from "@expo/vector-icons";
import * as Clipboard from "expo-clipboard";
import { router, useLocalSearchParams } from "expo-router";
import { useMemo, useState } from "react";
import { Alert, Linking, Pressable, ScrollView, Share, StyleSheet, Switch, Text, View, useColorScheme } from "react-native";
import { Colors, Fonts } from "@/constants/theme";
import { useDebts } from "@/context/debt-context";
import { formatMoney } from "@/lib/currency";
import { scheduleDebtReminder } from "@/lib/notifications";
import { remainingAmount } from "@/types/debt";

type Tone="friendly"|"formal"|"urgent";

export default function ReminderScreen(){
  const {id}=useLocalSearchParams<{id:string}>(); const colors=Colors[useColorScheme()==="dark"?"dark":"light"]; const {getDebt,setReminder}=useDebts(); const [tone,setTone]=useState<Tone>("friendly"); const [autoRemind,setAutoRemind]=useState(false); const debt=getDebt(id);
  const message=useMemo(()=>{if(!debt)return "";const amount=formatMoney(remainingAmount(debt),debt.currency);if(tone==="formal")return "Hello "+debt.person+", just a gentle reminder about the "+amount+" balance we have recorded. Please let me know when you expect to settle it. Thank you.";if(tone==="urgent")return "Hi "+debt.person+", this is a reminder about the outstanding "+amount+" balance. Please let me know when you can make the payment.";return "Hey "+debt.person+" 👋 Just a quick reminder about the "+amount+" you still have with me. No pressure — let me know when you can sort it out. Thanks!";},[debt,tone]);
  if(!debt)return <View style={[styles.center,{backgroundColor:colors.background}]}><Text style={[styles.notFound,{color:colors.text}]}>Debt not found.</Text></View>;
  const copy=async()=>{await Clipboard.setStringAsync(message);Alert.alert("Copied","Your reminder message is on the clipboard.")}; const share=async()=>{await Share.share({message})}; const whatsapp=()=>Linking.openURL("whatsapp://send?text="+encodeURIComponent(message)).catch(()=>share()); const sms=()=>Linking.openURL("sms:?body="+encodeURIComponent(message)).catch(()=>Alert.alert("SMS unavailable","Your phone could not open the SMS composer."));
  const schedule=async(enabled:boolean)=>{const dueDate=debt.dueDate;if(enabled&&!dueDate){Alert.alert("No due date","Add a due date to this debt before scheduling an automatic reminder.");return;}setAutoRemind(enabled);if(enabled){const reminderId=await scheduleDebtReminder(debt.person,dueDate,{title:"OwedBy reminder",body:message});if(reminderId)await setReminder(debt.id,reminderId);else setAutoRemind(false);}else await setReminder(debt.id,undefined);};
  return <ScrollView style={{backgroundColor:colors.background}} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.header}><Pressable onPress={()=>router.back()} style={styles.back}><Ionicons name="arrow-back" size={22} color={colors.text}/></Pressable><Text style={[styles.title,{color:colors.text}]}>Smart reminder</Text><View style={styles.back}/></View>
    <View style={[styles.hero,{backgroundColor:colors.primary}]}><View style={styles.heroIcon}><Ionicons name="chatbubble-ellipses" size={26} color="#fff"/></View><Text style={styles.heroTitle}>Remind {debt.person}</Text><Text style={styles.heroText}>Make the money conversation easier with a message that sounds like you.</Text><View style={styles.balance}><Text style={styles.balanceLabel}>OUTSTANDING</Text><Text style={styles.balanceAmount}>{formatMoney(remainingAmount(debt),debt.currency)}</Text></View></View>
    <Text style={[styles.label,{color:colors.text}]}>Choose a tone</Text><View style={styles.tones}>{[["friendly","Friendly"],["formal","Polite & Formal"],["urgent","Urgent"]].map(([v,label])=><Pressable key={v} onPress={()=>setTone(v as Tone)} style={[styles.tone,{backgroundColor:tone===v?colors.primary:colors.surface,borderColor:tone===v?colors.primary:colors.border}]}><Text style={[styles.toneText,{color:tone===v?"#fff":colors.textSecondary}]}>{label}</Text></Pressable>)}</View>
    <View style={styles.previewHead}><Text style={[styles.label,{color:colors.text}]}>Message preview</Text><View style={[styles.privatePill,{backgroundColor:colors.primarySoft}]}><Ionicons name="lock-closed-outline" size={11} color={colors.primary}/><Text style={[styles.privateText,{color:colors.primary}]}>Private</Text></View></View>
    <View style={[styles.preview,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.previewText,{color:colors.text}]}>{message}</Text></View>
    <View style={styles.actions}><Pressable onPress={whatsapp} style={[styles.whatsapp,{backgroundColor:colors.success}]}><Ionicons name="logo-whatsapp" size={20} color="#fff"/><Text style={styles.whiteText}>Share to WhatsApp</Text></Pressable><View style={styles.actionRow}><Pressable onPress={sms} style={[styles.action,{backgroundColor:colors.surface,borderColor:colors.border}]}><Ionicons name="chatbox-outline" size={19} color={colors.primary}/><Text style={[styles.actionText,{color:colors.text}]}>SMS</Text></Pressable><Pressable onPress={copy} style={[styles.action,{backgroundColor:colors.surface,borderColor:colors.border}]}><Ionicons name="copy-outline" size={19} color={colors.primary}/><Text style={[styles.actionText,{color:colors.text}]}>Copy</Text></Pressable></View></View>
    <View style={[styles.schedule,{backgroundColor:colors.surface,borderColor:colors.border}]}><View style={[styles.scheduleIcon,{backgroundColor:colors.warningSoft}]}><Ionicons name="notifications-outline" size={19} color={colors.warning}/></View><View style={{flex:1}}><Text style={[styles.scheduleTitle,{color:colors.text}]}>Auto-remind me</Text><Text style={[styles.scheduleText,{color:colors.textSecondary}]}>{debt.dueDate?"Schedule a private reminder for the due date.":"Add a due date to enable automatic reminders."}</Text></View><Switch disabled={!debt.dueDate} value={autoRemind} onValueChange={schedule} trackColor={{false:colors.surfaceSecondary,true:colors.primarySoft}} thumbColor={autoRemind?colors.primary:colors.textTertiary}/></View>
  </ScrollView>;
}
const styles=StyleSheet.create({content:{padding:20,paddingTop:30,paddingBottom:64},header:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginBottom:18},back:{width:44,height:44,alignItems:"center",justifyContent:"center"},title:{fontFamily:Fonts.bold,fontSize:21},hero:{borderRadius:22,padding:20},heroIcon:{width:52,height:52,borderRadius:17,backgroundColor:"rgba(255,255,255,.14)",alignItems:"center",justifyContent:"center"},heroTitle:{color:"#fff",fontFamily:Fonts.extraBold,fontSize:22,marginTop:15},heroText:{color:"rgba(255,255,255,.78)",fontFamily:Fonts.regular,fontSize:11,lineHeight:17,marginTop:5},balance:{marginTop:18,paddingTop:14,borderTopWidth:1,borderTopColor:"rgba(255,255,255,.15)"},balanceLabel:{color:"rgba(255,255,255,.65)",fontFamily:Fonts.bold,fontSize:8,letterSpacing:1},balanceAmount:{color:"#fff",fontFamily:Fonts.extraBold,fontSize:25,marginTop:4},label:{fontFamily:Fonts.semiBold,fontSize:13,marginTop:22,marginBottom:9},tones:{flexDirection:"row",gap:7},tone:{flex:1,minHeight:43,borderRadius:14,borderWidth:1,alignItems:"center",justifyContent:"center",paddingHorizontal:6},toneText:{fontFamily:Fonts.medium,fontSize:10,textAlign:"center"},previewHead:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"},privatePill:{paddingHorizontal:7,paddingVertical:4,borderRadius:8,flexDirection:"row",alignItems:"center",gap:3},privateText:{fontFamily:Fonts.bold,fontSize:8},preview:{borderRadius:18,borderWidth:1,padding:17,minHeight:132},previewText:{fontFamily:Fonts.regular,fontSize:13.5,lineHeight:21},actions:{gap:9,marginTop:16},whatsapp:{height:52,borderRadius:16,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:8},whiteText:{color:"#fff",fontFamily:Fonts.semiBold,fontSize:14},actionRow:{flexDirection:"row",gap:9},action:{flex:1,height:50,borderRadius:15,borderWidth:1,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:7},actionText:{fontFamily:Fonts.semiBold,fontSize:13},schedule:{marginTop:18,borderRadius:18,borderWidth:1,padding:14,flexDirection:"row",alignItems:"center",gap:10},scheduleIcon:{width:40,height:40,borderRadius:13,alignItems:"center",justifyContent:"center"},scheduleTitle:{fontFamily:Fonts.semiBold,fontSize:13},scheduleText:{fontFamily:Fonts.regular,fontSize:10,lineHeight:16,marginTop:3},center:{flex:1,alignItems:"center",justifyContent:"center"},notFound:{fontFamily:Fonts.semiBold}});
