import { Ionicons } from "@expo/vector-icons";
import { ScrollView, StyleSheet, Text, View, useColorScheme } from "react-native";
import { BottomNav } from "@/components/bottom-nav";
import { Colors, Fonts } from "@/constants/theme";
import { useDebts } from "@/context/debt-context";
import { useSettings } from "@/context/settings-context";
import { formatMoney } from "@/lib/currency";
import { currencyPaidTotals, currencyRecordedTotals, remainingAmount } from "@/types/debt";

export default function InsightsScreen() {
  const colors=Colors[useColorScheme()==="dark"?"dark":"light"]; const {debts}=useDebts(); const {defaultCurrency}=useSettings();
  const current=debts.filter(d=>d.currency===defaultCurrency); const receivable=current.filter(d=>d.type==="they_owe_me").reduce((s,d)=>s+remainingAmount(d),0); const payable=current.filter(d=>d.type==="i_owe_them").reduce((s,d)=>s+remainingAmount(d),0);
  const recorded=currencyRecordedTotals(current)[defaultCurrency]??0; const paid=currencyPaidTotals(current)[defaultCurrency]??0; const recovery=recorded?Math.min(1,paid/recorded):0; const net=receivable-payable; const openCount=current.filter(d=>remainingAmount(d)>0).length;
  const dueSoon=current.filter(d=>{if(!d.dueDate||remainingAmount(d)<=0)return false;const days=(new Date(d.dueDate).setHours(0,0,0,0)-new Date().setHours(0,0,0,0))/86400000;return days>=0&&days<=7}).length;
  const overdue=current.filter(d=>{if(!d.dueDate||remainingAmount(d)<=0)return false;return new Date(d.dueDate).setHours(0,0,0,0)<new Date().setHours(0,0,0,0)}).length;
  const categories=Object.entries(current.reduce<Record<string,number>>((a,d)=>{a[d.category]=(a[d.category]??0)+remainingAmount(d);return a},{})).sort((a,b)=>b[1]-a[1]).slice(0,4);
  return <View style={[styles.container,{backgroundColor:colors.background}]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.header}><View style={{flex:1}}><Text style={[styles.kicker,{color:colors.primary}]}>YOUR MONEY PICTURE</Text><Text style={[styles.title,{color:colors.text}]}>Insights</Text><Text style={[styles.sub,{color:colors.textSecondary}]}>A calm view of what is outstanding.</Text></View><View style={[styles.currency,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.currencyCode,{color:colors.text}]}>{defaultCurrency}</Text></View></View>
    <View style={[styles.hero,{backgroundColor:net>=0?colors.primary:colors.terracotta}]}><View style={{flex:1}}><Text style={styles.heroLabel}>NET STANDING</Text><Text style={styles.heroValue}>{net>=0?"+":"-"}{formatMoney(Math.abs(net),defaultCurrency)}</Text><Text style={styles.heroHint}>{openCount} open balance{openCount===1?"":"s"} · {defaultCurrency}</Text></View><View style={styles.heroIcon}><Ionicons name={net>=0?"trending-up":"trending-down"} size={27} color="#fff"/></View></View>
    <View style={styles.grid}><View style={[styles.metric,{backgroundColor:colors.surface,borderColor:colors.border}]}><View style={[styles.metricIcon,{backgroundColor:colors.successSoft}]}><Ionicons name="arrow-down" size={17} color={colors.success}/></View><Text style={[styles.metricLabel,{color:colors.textSecondary}]}>People owe you</Text><Text style={[styles.metricValue,{color:colors.text}]}>{formatMoney(receivable,defaultCurrency)}</Text></View><View style={[styles.metric,{backgroundColor:colors.surface,borderColor:colors.border}]}><View style={[styles.metricIcon,{backgroundColor:colors.terracottaSoft}]}><Ionicons name="arrow-up" size={17} color={colors.terracotta}/></View><Text style={[styles.metricLabel,{color:colors.textSecondary}]}>You owe</Text><Text style={[styles.metricValue,{color:colors.text}]}>{formatMoney(payable,defaultCurrency)}</Text></View></View>
    <View style={[styles.card,{backgroundColor:colors.surface,borderColor:colors.border}]}><View style={styles.cardHead}><View style={{flex:1}}><Text style={[styles.cardTitle,{color:colors.text}]}>Recovery progress</Text><Text style={[styles.cardSub,{color:colors.textSecondary}]}>How much of your recorded money has come back.</Text></View><Text style={[styles.percent,{color:colors.success}]}>{Math.round(recovery*100)}%</Text></View><View style={[styles.track,{backgroundColor:colors.surfaceSecondary}]}><View style={[styles.fill,{backgroundColor:colors.success,width:(recovery*100)+"%"}]}/></View><View style={styles.recoveryRow}><Text style={[styles.small,{color:colors.textSecondary}]}>{formatMoney(paid,defaultCurrency)} recovered</Text><Text style={[styles.small,{color:colors.textSecondary}]}>{formatMoney(recorded,defaultCurrency)} recorded</Text></View></View>
    <View style={styles.grid}><View style={[styles.mini,{backgroundColor:colors.warningSoft}]}><Ionicons name="calendar-outline" size={19} color={colors.warning}/><Text style={[styles.miniNumber,{color:colors.text}]}>{dueSoon}</Text><Text style={[styles.miniLabel,{color:colors.textSecondary}]}>Due soon</Text></View><View style={[styles.mini,{backgroundColor:colors.dangerSoft}]}><Ionicons name="alert-circle-outline" size={19} color={colors.danger}/><Text style={[styles.miniNumber,{color:colors.text}]}>{overdue}</Text><Text style={[styles.miniLabel,{color:colors.textSecondary}]}>Overdue</Text></View><View style={[styles.mini,{backgroundColor:colors.primarySoft}]}><Ionicons name="layers-outline" size={19} color={colors.primary}/><Text style={[styles.miniNumber,{color:colors.text}]}>{openCount}</Text><Text style={[styles.miniLabel,{color:colors.textSecondary}]}>Open</Text></View></View>
    <View style={[styles.card,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.cardTitle,{color:colors.text}]}>Open balances by category</Text><Text style={[styles.cardSub,{color:colors.textSecondary}]}>Where your outstanding money is sitting.</Text>{categories.length?categories.map(([category,value],i)=><View key={category} style={[styles.categoryRow,{borderBottomColor:colors.border}]}><View style={[styles.categoryIcon,{backgroundColor:i===0?colors.primarySoft:colors.surfaceSecondary}]}><Ionicons name="ellipse" size={8} color={i===0?colors.primary:colors.textTertiary}/></View><Text style={[styles.categoryName,{color:colors.text}]}>{category.charAt(0).toUpperCase()+category.slice(1)}</Text><Text style={[styles.categoryValue,{color:colors.text}]}>{formatMoney(value,defaultCurrency)}</Text></View>):<Text style={[styles.emptyText,{color:colors.textSecondary}]}>Add debts to see your categories.</Text>}</View>
    <View style={[styles.tip,{backgroundColor:colors.surfaceSecondary}]}><View style={[styles.tipIcon,{backgroundColor:colors.surface}]}><Ionicons name="sparkles-outline" size={18} color={colors.primary}/></View><Text style={[styles.tipText,{color:colors.textSecondary}]}>Currencies stay separate, so OwedBy never invents an exchange rate.</Text></View>
  </ScrollView><BottomNav/></View>;
}
const styles=StyleSheet.create({container:{flex:1},content:{padding:20,paddingTop:30,paddingBottom:112},header:{flexDirection:"row",justifyContent:"space-between",alignItems:"flex-start",marginBottom:18},kicker:{fontFamily:Fonts.bold,fontSize:9,letterSpacing:1.2},title:{fontFamily:Fonts.extraBold,fontSize:31,marginTop:3},sub:{fontFamily:Fonts.regular,fontSize:12,marginTop:4},currency:{paddingHorizontal:11,paddingVertical:9,borderRadius:13,borderWidth:1},currencyCode:{fontFamily:Fonts.bold,fontSize:10},hero:{minHeight:124,borderRadius:22,padding:20,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},heroLabel:{color:"rgba(255,255,255,.68)",fontFamily:Fonts.bold,fontSize:8,letterSpacing:1},heroValue:{color:"#fff",fontFamily:Fonts.extraBold,fontSize:27,marginTop:7},heroHint:{color:"rgba(255,255,255,.78)",fontFamily:Fonts.regular,fontSize:10,marginTop:4},heroIcon:{width:48,height:48,borderRadius:16,backgroundColor:"rgba(255,255,255,.14)",alignItems:"center",justifyContent:"center"},grid:{flexDirection:"row",gap:9,marginTop:11},metric:{flex:1,minHeight:132,borderRadius:18,borderWidth:1,padding:15},metricIcon:{width:33,height:33,borderRadius:11,alignItems:"center",justifyContent:"center",marginBottom:12},metricLabel:{fontFamily:Fonts.medium,fontSize:10},metricValue:{fontFamily:Fonts.extraBold,fontSize:19,marginTop:5},card:{marginTop:11,borderRadius:19,borderWidth:1,padding:17},cardHead:{flexDirection:"row",justifyContent:"space-between",alignItems:"flex-start"},cardTitle:{fontFamily:Fonts.bold,fontSize:15},cardSub:{fontFamily:Fonts.regular,fontSize:10,lineHeight:16,marginTop:3},percent:{fontFamily:Fonts.extraBold,fontSize:18},track:{height:9,borderRadius:5,overflow:"hidden",marginTop:16},fill:{height:"100%",borderRadius:5},recoveryRow:{flexDirection:"row",justifyContent:"space-between",marginTop:8},small:{fontFamily:Fonts.medium,fontSize:9},mini:{flex:1,minHeight:92,borderRadius:17,padding:13},miniNumber:{fontFamily:Fonts.extraBold,fontSize:21,marginTop:5},miniLabel:{fontFamily:Fonts.medium,fontSize:9,marginTop:1},categoryRow:{minHeight:48,flexDirection:"row",alignItems:"center",borderBottomWidth:StyleSheet.hairlineWidth},categoryIcon:{width:25,height:25,borderRadius:8,alignItems:"center",justifyContent:"center",marginRight:9},categoryName:{flex:1,fontFamily:Fonts.medium,fontSize:12},categoryValue:{fontFamily:Fonts.bold,fontSize:11},emptyText:{fontFamily:Fonts.regular,fontSize:12,marginTop:13},tip:{marginTop:11,borderRadius:17,padding:13,flexDirection:"row",gap:9,alignItems:"center"},tipIcon:{width:36,height:36,borderRadius:11,alignItems:"center",justifyContent:"center"},tipText:{flex:1,fontFamily:Fonts.regular,fontSize:10,lineHeight:16}});
