import { Ionicons } from "@expo/vector-icons";
import { ScrollView, StyleSheet, Text, View, useColorScheme } from "react-native";
import { BottomNav } from "@/components/bottom-nav";
import { Colors, Fonts, Radius } from "@/constants/theme";
import { useDebts } from "@/context/debt-context";
import { paymentProgress, remainingAmount } from "@/types/debt";
import { formatMoney } from "@/lib/currency";
import { useSettings } from "@/context/settings-context";

export default function InsightsScreen(){const colors=Colors[useColorScheme()==="dark"?"dark":"light"];const {debts}=useDebts();const {defaultCurrency}=useSettings();const currencyDebts=debts.filter(d=>d.currency===defaultCurrency);const totalOwedToMe=currencyDebts.filter(d=>d.type==="they_owe_me").reduce((s,d)=>s+remainingAmount(d),0);const totalIOwe=currencyDebts.filter(d=>d.type==="i_owe_them").reduce((s,d)=>s+remainingAmount(d),0);const totalRecorded=currencyDebts.reduce((s,d)=>s+d.amount,0);const recovered=currencyDebts.reduce((s,d)=>s+d.amount-remainingAmount(d),0);const progress=totalRecorded?recovered/totalRecorded:0;const dueSoon=currencyDebts.filter(d=>remainingAmount(d)>0&&d.dueDate&&((new Date(d.dueDate).getTime()-Date.now())/86400000)<=7).length;return <View style={[styles.container,{backgroundColor:colors.background}]}><ScrollView contentContainerStyle={styles.content}><Text style={[styles.title,{color:colors.text}]}>Insights</Text><Text style={[styles.sub,{color:colors.textSecondary}]}>A simple view of your money notebook.</Text><View style={styles.grid}><View style={[styles.card,{backgroundColor:colors.surface}]}><Ionicons name="arrow-down" size={20} color={colors.success}/><Text style={[styles.label,{color:colors.textSecondary}]}>Receivable</Text><Text style={[styles.value,{color:colors.text}]}>{formatMoney(totalOwedToMe,defaultCurrency)}</Text></View><View style={[styles.card,{backgroundColor:colors.surface}]}><Ionicons name="arrow-up" size={20} color={colors.terracotta}/><Text style={[styles.label,{color:colors.textSecondary}]}>Payable</Text><Text style={[styles.value,{color:colors.text}]}>{formatMoney(totalIOwe,defaultCurrency)}</Text></View></View><View style={[styles.big,{backgroundColor:colors.surface}]}><Text style={[styles.cardTitle,{color:colors.text}]}>Recovery progress</Text><Text style={[styles.bigValue,{color:colors.text}]}>{Math.round(progress*100)}%</Text><View style={[styles.track,{backgroundColor:colors.surfaceSecondary}]}><View style={[styles.fill,{backgroundColor:colors.primary,width:(progress*100)+"%"}]}/></View><Text style={[styles.help,{color:colors.textSecondary}]}>{formatMoney(recovered,defaultCurrency)} recovered from {formatMoney(totalRecorded,defaultCurrency)} recorded.</Text></View><View style={[styles.big,{backgroundColor:colors.surface}]}><Text style={[styles.cardTitle,{color:colors.text}]}>Due soon</Text><Text style={[styles.bigValue,{color:colors.text}]}>{dueSoon}</Text><Text style={[styles.help,{color:colors.textSecondary}]}>open debt{dueSoon===1?"":"s"} due within the next 7 days.</Text></View></ScrollView><BottomNav/></View>}
const styles=StyleSheet.create({container:{flex:1},content:{padding:24,paddingTop:48,paddingBottom:110},title:{fontFamily:Fonts.extraBold,fontSize:30},sub:{fontFamily:Fonts.regular,fontSize:13,marginTop:4,marginBottom:24},grid:{flexDirection:"row",gap:8},card:{flex:1,borderRadius:Radius.large,padding:16},label:{fontFamily:Fonts.medium,fontSize:11,marginTop:12},value:{fontFamily:Fonts.extraBold,fontSize:20,marginTop:3},big:{borderRadius:Radius.large,padding:20,marginTop:12},cardTitle:{fontFamily:Fonts.semiBold,fontSize:16},bigValue:{fontFamily:Fonts.extraBold,fontSize:32,marginTop:10},track:{height:9,borderRadius:5,overflow:"hidden",marginTop:10},fill:{height:"100%",borderRadius:5},help:{fontFamily:Fonts.regular,fontSize:12,lineHeight:19,marginTop:8}});
