import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View, useColorScheme } from "react-native";
import { BottomNav } from "@/components/bottom-nav";
import { Colors, Fonts, Radius, Spacing } from "@/constants/theme";
import { useDebts } from "@/context/debt-context";
import { remainingAmount } from "@/types/debt";

export default function PeopleScreen(){const colors=Colors[useColorScheme()==="dark"?"dark":"light"];const {debts}=useDebts();const people=Array.from(new Map(debts.map(d=>[d.person.trim().toLowerCase(),d])).values());return <View style={[styles.container,{backgroundColor:colors.background}]}><ScrollView contentContainerStyle={styles.content}><Text style={[styles.title,{color:colors.text}]}>People</Text><Text style={[styles.sub,{color:colors.textSecondary}]}>Everyone in your money notebook.</Text><View style={styles.list}>{people.map(p=>{const personDebts=debts.filter(d=>d.person.trim().toLowerCase()===p.person.trim().toLowerCase());const total=personDebts.reduce((sum,d)=>sum+remainingAmount(d),0);return <Pressable key={p.person} onPress={()=>router.push({pathname:"/debt/[id]",params:{id:(debts.filter(d=>d.person.trim().toLowerCase()===p.person.trim().toLowerCase()).find(d=>remainingAmount(d)>0)??p).id}})} style={[styles.row,{backgroundColor:colors.surface,borderColor:colors.border}]}><View style={[styles.avatar,{backgroundColor:p.type==="they_owe_me"?colors.successSoft:colors.terracottaSoft}]}><Text style={[styles.initial,{color:p.type==="they_owe_me"?colors.success:colors.terracotta}]}>{p.person[0].toUpperCase()}</Text></View><View style={{flex:1}}><Text style={[styles.name,{color:colors.text}]}>{p.person}</Text><Text style={[styles.meta,{color:colors.textSecondary}]}>{personDebts.length} debt{personDebts.length===1?"":"s"} · {personDebts.reduce((sum,d)=>sum+d.payments.length,0)} payment{personDebts.reduce((sum,d)=>sum+d.payments.length,0)===1?"":"s"}</Text></View><Text style={[styles.amount,{color:colors.text}]}>₦{total.toLocaleString("en-NG")}</Text><Ionicons name="chevron-forward" size={16} color={colors.textTertiary}/></Pressable>})}</View>{!people.length?<View style={[styles.empty,{backgroundColor:colors.surface}]}><Text style={[styles.emptyText,{color:colors.textSecondary}]}>Add a debt to start your people ledger.</Text></View>:null}</ScrollView><BottomNav/></View>}
const styles=StyleSheet.create({container:{flex:1},content:{padding:24,paddingTop:48,paddingBottom:110},title:{fontFamily:Fonts.extraBold,fontSize:30},sub:{fontFamily:Fonts.regular,fontSize:13,marginTop:4,marginBottom:24},list:{gap:8},row:{minHeight:76,borderRadius:16,borderWidth:1,padding:12,flexDirection:"row",alignItems:"center"},avatar:{width:44,height:44,borderRadius:22,alignItems:"center",justifyContent:"center",marginRight:12},initial:{fontFamily:Fonts.bold,fontSize:17},name:{fontFamily:Fonts.semiBold,fontSize:14},meta:{fontFamily:Fonts.regular,fontSize:11,marginTop:4},amount:{fontFamily:Fonts.bold,fontSize:13,marginRight:8},empty:{padding:28,borderRadius:16},emptyText:{fontFamily:Fonts.regular,textAlign:"center"}});
