import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View, useColorScheme } from "react-native";
import { Colors, Fonts, Radius, Spacing } from "@/constants/theme";
import { CURRENCIES } from "@/lib/currency";
import { useSettings } from "@/context/settings-context";

export default function SettingsScreen() {
  const colors=Colors[useColorScheme()==="dark"?"dark":"light"]; const {defaultCurrency,setDefaultCurrency}=useSettings();
  return <View style={[styles.container,{backgroundColor:colors.background}]}>
    <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
      <View style={styles.header}><Pressable onPress={()=>router.back()} style={styles.back}><Ionicons name="arrow-back" size={22} color={colors.text}/></Pressable><View style={{flex:1,alignItems:"center"}}><Text style={[styles.kicker,{color:colors.primary}]}>OWEDBY</Text><Text style={[styles.title,{color:colors.text}]}>Settings</Text></View><View style={styles.back}/></View>
      <View style={[styles.hero,{backgroundColor:colors.primary}]}>
        <View style={styles.heroTop}><View style={styles.heroIcon}><Ionicons name="options-outline" size={23} color="#fff"/></View><View style={styles.heroBadge}><Ionicons name="shield-checkmark-outline" size={13} color="#fff"/><Text style={styles.heroBadgeText}>Private</Text></View></View>
        <Text style={styles.heroTitle}>Your money, your rules.</Text><Text style={styles.heroText}>Set the currency OwedBy uses when you create a new debt. Existing debts never get silently converted.</Text>
      </View>
      <Text style={[styles.sectionTitle,{color:colors.text}]}>Money preferences</Text>
      <View style={[styles.list,{backgroundColor:colors.surface,borderColor:colors.border}]}>
        <View style={[styles.listIntro,{borderBottomColor:colors.border}]}><View style={[styles.introIcon,{backgroundColor:colors.primarySoft}]}><Ionicons name="cash-outline" size={20} color={colors.primary}/></View><View style={{flex:1}}><Text style={[styles.introTitle,{color:colors.text}]}>Default currency</Text><Text style={[styles.introText,{color:colors.textSecondary}]}>Used for new debts only.</Text></View><View style={[styles.current,{backgroundColor:colors.primarySoft}]}><Text style={[styles.currentText,{color:colors.primary}]}>{defaultCurrency}</Text></View></View>
        {CURRENCIES.map((c,index)=>{const selected=c.code===defaultCurrency;return <Pressable key={c.code} onPress={()=>setDefaultCurrency(c.code)} style={[styles.row,{borderBottomColor:colors.border}]}><View style={[styles.symbol,{backgroundColor:selected?colors.primarySoft:colors.surfaceSecondary}]}><Text style={[styles.symbolText,{color:selected?colors.primary:colors.textSecondary}]}>{c.symbol}</Text></View><View style={styles.rowText}><Text style={[styles.name,{color:colors.text}]}>{c.name}</Text><Text style={[styles.code,{color:colors.textSecondary}]}>{c.code}</Text></View>{selected?<View style={[styles.selected,{backgroundColor:colors.primarySoft}]}><Ionicons name="checkmark" size={15} color={colors.primary}/><Text style={[styles.selectedText,{color:colors.primary}]}>Default</Text></View>:<Ionicons name="chevron-forward" size={16} color={colors.textTertiary}/>}</Pressable>})}
      </View>
      <View style={[styles.infoCard,{backgroundColor:colors.surfaceSecondary}]}><Ionicons name="lock-closed-outline" size={20} color={colors.primary}/><View style={{flex:1}}><Text style={[styles.infoTitle,{color:colors.text}]}>Local-first privacy</Text><Text style={[styles.infoText,{color:colors.textSecondary}]}>OwedBy is designed around a personal ledger. No bank login, card number or BVN is required to track a debt.</Text></View></View>
    </ScrollView>
  </View>;
}
const styles=StyleSheet.create({container:{flex:1},content:{padding:20,paddingTop:30,paddingBottom:60},header:{flexDirection:"row",alignItems:"center",marginBottom:18},back:{width:44,height:44,alignItems:"center",justifyContent:"center"},kicker:{fontFamily:Fonts.bold,fontSize:8,letterSpacing:1.3},title:{fontFamily:Fonts.extraBold,fontSize:23,marginTop:1},hero:{borderRadius:22,padding:20,minHeight:178},heroTop:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},heroIcon:{width:46,height:46,borderRadius:15,backgroundColor:"rgba(255,255,255,.15)",alignItems:"center",justifyContent:"center"},heroBadge:{paddingHorizontal:9,paddingVertical:6,borderRadius:10,backgroundColor:"rgba(255,255,255,.14)",flexDirection:"row",alignItems:"center",gap:5},heroBadgeText:{color:"#fff",fontFamily:Fonts.semiBold,fontSize:9},heroTitle:{color:"#fff",fontFamily:Fonts.extraBold,fontSize:22,marginTop:27},heroText:{color:"rgba(255,255,255,.78)",fontFamily:Fonts.regular,fontSize:11,lineHeight:17,marginTop:5},sectionTitle:{fontFamily:Fonts.bold,fontSize:16,marginTop:23,marginBottom:10},list:{borderRadius:20,borderWidth:1,overflow:"hidden"},listIntro:{minHeight:76,padding:13,flexDirection:"row",alignItems:"center",borderBottomWidth:1},introIcon:{width:42,height:42,borderRadius:13,alignItems:"center",justifyContent:"center",marginRight:11},introTitle:{fontFamily:Fonts.semiBold,fontSize:13},introText:{fontFamily:Fonts.regular,fontSize:10,marginTop:3},current:{paddingHorizontal:9,paddingVertical:6,borderRadius:9},currentText:{fontFamily:Fonts.bold,fontSize:9},row:{minHeight:64,paddingHorizontal:13,flexDirection:"row",alignItems:"center",borderBottomWidth:StyleSheet.hairlineWidth},symbol:{width:39,height:39,borderRadius:12,alignItems:"center",justifyContent:"center",marginRight:11},symbolText:{fontFamily:Fonts.bold,fontSize:15},rowText:{flex:1},name:{fontFamily:Fonts.semiBold,fontSize:12.5},code:{fontFamily:Fonts.regular,fontSize:10,marginTop:2},selected:{paddingHorizontal:8,paddingVertical:5,borderRadius:8,flexDirection:"row",alignItems:"center",gap:3},selectedText:{fontFamily:Fonts.bold,fontSize:8},infoCard:{marginTop:12,borderRadius:18,padding:14,flexDirection:"row",gap:10,alignItems:"flex-start"},infoTitle:{fontFamily:Fonts.semiBold,fontSize:12},infoText:{fontFamily:Fonts.regular,fontSize:10,lineHeight:16,marginTop:3}});
